"""allow_null_fields_in_time_slices

Revision ID: 39492233c0a3
Revises: b530655efe65
Create Date: 2025-11-11 11:30:03.391439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39492233c0a3'
down_revision: Union[str, Sequence[str], None] = 'b530655efe65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_deleted_task_expiry_at', 'deletedtask', ['expiry_at'], unique=False)
    op.create_index('ix_deleted_task_task_id', 'deletedtask', ['task_id'], unique=False)
    op.alter_column('task', 'position',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Sort position for ordering tasks within the same parent',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('timeslice', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('timeslice', 'duration_ms',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('timeslice', 'efficiency_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeslice', 'efficiency_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('timeslice', 'duration_ms',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('timeslice', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('task', 'position',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sort position for ordering tasks within the same parent',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index('ix_deleted_task_task_id', table_name='deletedtask')
    op.drop_index('ix_deleted_task_expiry_at', table_name='deletedtask')
    # ### end Alembic commands ###
