"""add gtd and scheduling fields

Revision ID: 6bffedbf393a
Revises: 757673d55512
Create Date: 2025-11-19 18:25:45.003347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bffedbf393a'
down_revision: Union[str, Sequence[str], None] = '757673d55512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create task_list enum type (manual adjustment - autogenerate cannot detect new enum types)
    task_list_enum = postgresql.ENUM('INBOX', 'TODAY', 'NEXT', 'SOMEDAY', 'WAITING', name='task_list', create_type=True)
    task_list_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('task', sa.Column('list', task_list_enum, nullable=False, server_default='INBOX', comment='GTD workflow list: inbox, today, next, someday, waiting'))
    op.add_column('task', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Tags for categorization and filtering (e.g., @home, #coding)'))
    op.add_column('task', sa.Column('scheduled_date', sa.Date(), nullable=True, comment='Date when the task is scheduled to be done'))
    op.add_column('task', sa.Column('scheduled_time', sa.Time(), nullable=True, comment='Optional time of day when task is scheduled'))
    op.alter_column('task', 'is_ddl',
               existing_type=sa.BOOLEAN(),
               comment='If True, task becomes locked and read-only after due_at expires',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_ddl',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If True, task becomes locked and read-only after due_at expires',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('task', 'scheduled_time')
    op.drop_column('task', 'scheduled_date')
    op.drop_column('task', 'tags')
    op.drop_column('task', 'list')

    # Drop task_list enum type
    task_list_enum = postgresql.ENUM(name='task_list')
    task_list_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
