"""add_is_ddl_field_to_task

Revision ID: 757673d55512
Revises: 8a253c4dcbc8
Create Date: 2025-11-11 17:59:03.909586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757673d55512'
down_revision: Union[str, Sequence[str], None] = '8a253c4dcbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('task', sa.Column('is_ddl', sa.Boolean(), nullable=True, comment='If True, task becomes locked and read-only after due_at expires'))
    # Set default value for existing rows
    op.execute("UPDATE task SET is_ddl = false WHERE is_ddl IS NULL")
    # Now make it NOT NULL
    op.alter_column('task', 'is_ddl', nullable=False, server_default=sa.false())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_ddl')
    # ### end Alembic commands ###
