"""allow_null_estimated_time_ms

Revision ID: 8a253c4dcbc8
Revises: 39492233c0a3
Create Date: 2025-11-11 15:42:26.105562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a253c4dcbc8'
down_revision: Union[str, Sequence[str], None] = '39492233c0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'estimated_time_ms',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'estimated_time_ms',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
